"use client"
import { useState, useCallback, useRef, useEffect } from "react"
import { useWorkItems, useScheduleStore } from "@/stores/scheduleStore"
import { MOCK_USERS } from "@/lib/mock-data/users"
import { cn } from "@/lib/utils"
import type { WorkItem } from "@/lib/types"
import {
  GitFork, GitBranch, GitCommit, GitPullRequest, Terminal,
  Code2, ExternalLink, CheckCircle2, Zap, Copy, Loader2,
  User, RotateCcw, Upload, FileCode2, GitMerge,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { VsCodeExportModal } from "@/components/schedule/vscode-export-modal"

const FAKE_REPO    = "slalom/meridian-bank-digital-platform"
const FAKE_USER    = "slalom-delivery-bot"
const FAKE_PR_BASE = "https://github.com/slalom/meridian-bank-digital-platform/pull"

type GitStatus =
  | "idle" | "generating" | "ready"
  | "committing" | "committed"
  | "pushing" | "pushed" | "pr_created"

interface LogEntry { type: "cmd" | "info" | "ok" | "err" | "remote"; text: string }

interface TaskGitState {
  status:        GitStatus
  code:          string
  displayCode:   string
  branch:        string
  commitMessage: string
  commitHash:    string
  prNumber:      number
  log:           LogEntry[]
}

const DEFAULT_STATE: TaskGitState = {
  status: "idle", code: "", displayCode: "",
  branch: "", commitMessage: "", commitHash: "",
  prNumber: 0, log: [],
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
function slugify(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 30).replace(/-$/, "")
}

function toPascal(s: string) {
  return s.replace(/(?:^|[\s-_])(\w)/g, (_, c: string) => c.toUpperCase()).replace(/[\s-_]/g, "")
}

function randomHash() {
  return Math.random().toString(16).slice(2, 9)
}

function getBranch(item: WorkItem): string {
  return `feature/${item.id}-${slugify(item.title)}`
}

function getCommitMsg(item: WorkItem): string {
  const t = item.title.toLowerCase()
  const prefix =
    t.includes("test") || t.includes("spec")       ? "test"     :
    t.includes("migrat") || t.includes("database")  ? "chore"    :
    t.includes("fix") || t.includes("bug")          ? "fix"      :
    t.includes("refactor")                          ? "refactor" :
    "feat"
  return `${prefix}: implement ${item.title.toLowerCase()} (WBS ${item.wbsNumber})`
}

function getFileName(item: WorkItem): string {
  const t    = item.title.toLowerCase()
  const slug = slugify(item.title)
  if (t.includes("migrat") || t.includes("profiling") || t.includes("database")) return `migrations/${slug}.sql`
  if (t.includes("test")   || t.includes("spec"))    return `tests/${slug}.test.ts`
  if (t.includes("auth")   || t.includes("component") || t.includes("portal") || t.includes("management"))
                                                      return `src/components/${toPascal(item.title)}.tsx`
  if (t.includes("api")    || t.includes("route") || t.includes("payment") || t.includes("integration") || t.includes("psd2"))
                                                      return `src/routes/${slug}.ts`
  if (t.includes("service") || t.includes("push") || t.includes("firebase") || t.includes("notification") || t.includes("script"))
                                                      return `src/services/${slug}.service.ts`
  return `src/utils/${slug}.ts`
}

function generateCode(item: WorkItem): string {
  const t    = item.title.toLowerCase()
  const name = toPascal(item.title)
  const slug = slugify(item.title)
  const tbl  = slug.replace(/-/g, "_")

  if (t.includes("migrat") || t.includes("profiling") || t.includes("database")) {
    return `-- ${item.title}
-- WBS: ${item.wbsNumber} | Generated by ${FAKE_USER}
-- Repo: ${FAKE_REPO}
-- Created: ${new Date().toISOString().split("T")[0]}
-- Context: Meridian Bank — Digital Banking Platform v3.0

BEGIN;

CREATE TABLE IF NOT EXISTS ${tbl} (
  id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id     VARCHAR(50)  NOT NULL,
  account_number  VARCHAR(30)  NOT NULL,
  channel         VARCHAR(20)  NOT NULL DEFAULT 'mobile',  -- mobile | web | api
  status          VARCHAR(20)  NOT NULL DEFAULT 'active',  -- active | suspended | closed
  currency        CHAR(3)      NOT NULL DEFAULT 'GBP',
  metadata        JSONB        NOT NULL DEFAULT '{}',
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_${tbl}_account   ON ${tbl} (account_number);
CREATE        INDEX IF NOT EXISTS idx_${tbl}_customer  ON ${tbl} (customer_id);
CREATE        INDEX IF NOT EXISTS idx_${tbl}_status    ON ${tbl} (status);
CREATE        INDEX IF NOT EXISTS idx_${tbl}_created   ON ${tbl} (created_at DESC);

-- Account activity summary view (used by dashboard and compliance reporting)
CREATE OR REPLACE VIEW v_${tbl}_summary AS
  SELECT
    customer_id,
    COUNT(*)                                    AS total_accounts,
    COUNT(*) FILTER (WHERE status = 'active')   AS active_accounts,
    COUNT(*) FILTER (WHERE channel = 'mobile')  AS mobile_accounts,
    MAX(updated_at)                             AS last_activity
  FROM   ${tbl}
  GROUP  BY customer_id;

-- Backfill from legacy core banking system (Temenos T24 export)
INSERT INTO ${tbl} (customer_id, account_number, channel, status, currency)
  SELECT
    t24_customer_id,
    t24_account_number,
    'web',
    CASE WHEN t24_status = 'A' THEN 'active' ELSE 'suspended' END,
    COALESCE(t24_currency, 'GBP')
  FROM   legacy_core.t24_accounts
  WHERE  migrated_at IS NULL
  ON     CONFLICT (account_number) DO NOTHING;

UPDATE legacy_core.t24_accounts
SET    migrated_at = NOW()
WHERE  migrated_at IS NULL;

COMMIT;
-- Rollback: DROP TABLE IF EXISTS ${tbl} CASCADE; DROP VIEW IF EXISTS v_${tbl}_summary;`
  }

  if (t.includes("test") || t.includes("spec")) {
    return `import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { ${name}Service } from '../services/${slug}.service'
import { db } from '../lib/db'

// ${item.title}
// WBS: ${item.wbsNumber} | Story Points: ${item.storyPoints ?? "?"}

vi.mock('../lib/db')

const MOCK_CUSTOMER_ID = 'cust-MB-001'
const MOCK_ACCOUNT = {
  id:             'acc-uuid-001',
  customer_id:    MOCK_CUSTOMER_ID,
  account_number: 'GB29NWBK60161331926819',
  channel:        'mobile',
  status:         'active',
  currency:       'GBP',
}

describe('${name}Service', () => {
  beforeEach(() => vi.clearAllMocks())
  afterEach(() => vi.restoreAllMocks())

  describe('findAll', () => {
    it('returns empty array when no accounts exist for customer', async () => {
      vi.mocked(db.query).mockResolvedValue({ rows: [] } as any)
      const result = await ${name}Service.findAll({ customerId: MOCK_CUSTOMER_ID })
      expect(result).toEqual([])
      expect(db.query).toHaveBeenCalledWith(
        expect.stringContaining('WHERE customer_id'),
        [MOCK_CUSTOMER_ID]
      )
    })

    it('returns paginated results filtered by channel', async () => {
      const mockRows = [
        { ...MOCK_ACCOUNT, id: 'acc-uuid-001', channel: 'mobile' },
        { ...MOCK_ACCOUNT, id: 'acc-uuid-002', channel: 'web', account_number: 'GB29NWBK60161331926820' },
      ]
      vi.mocked(db.query).mockResolvedValue({ rows: mockRows } as any)
      const result = await ${name}Service.findAll({ customerId: MOCK_CUSTOMER_ID, page: 1 })
      expect(result).toHaveLength(2)
      expect(result[0]).toHaveProperty('account_number', 'GB29NWBK60161331926819')
    })
  })

  describe('create', () => {
    it('creates an account record and returns it with an id', async () => {
      const payload = { customer_id: MOCK_CUSTOMER_ID, account_number: 'GB29NWBK60161331926821', channel: 'mobile' }
      vi.mocked(db.query).mockResolvedValue({ rows: [{ id: 'new-uuid', ...payload, currency: 'GBP', status: 'active' }] } as any)
      const result = await ${name}Service.create(payload)
      expect(result).toHaveProperty('id', 'new-uuid')
      expect(result.currency).toBe('GBP')
    })

    it('throws validation error when account_number is missing', async () => {
      await expect(
        ${name}Service.create({ customer_id: MOCK_CUSTOMER_ID } as any)
      ).rejects.toThrow('account_number is required')
    })

    it('throws when customer_id is missing', async () => {
      await expect(
        ${name}Service.create({ account_number: 'GB29NWBK60161331926821' } as any)
      ).rejects.toThrow()
    })
  })
})`
  }

  if (t.includes("auth") || t.includes("component") || t.includes("portal") || t.includes("management") || t.includes("ui") || t.includes("biometric")) {
    return `'use client'
import { useState, useEffect, useCallback } from 'react'
import { useRouter } from 'next/navigation'
// ${item.title}
// WBS: ${item.wbsNumber} | Story Points: ${item.storyPoints ?? "?"}
// Assignee: ${MOCK_USERS.find(u => u.id === item.assigneeId)?.name ?? "Unassigned"}

interface ${name}Props {
  customerId: string
  onSuccess?: (data: unknown) => void
  className?: string
}

export function ${name}({ customerId, onSuccess, className }: ${name}Props) {
  const router    = useRouter()
  const [data,    setData]    = useState<unknown[]>([])
  const [loading, setLoading] = useState(true)
  const [error,   setError]   = useState<string | null>(null)
  const [query,   setQuery]   = useState('')

  const fetchData = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const params = new URLSearchParams({ customerId, q: query })
      const res    = await fetch(\`/api/${slug}?\${params}\`, {
        headers: { 'X-Auth-Source': 'auth0', 'X-Client-Channel': 'web' },
      })
      if (!res.ok) throw new Error(\`HTTP \${res.status}\`)
      const json = await res.json()
      setData(json.data ?? [])
      onSuccess?.(json.data)
    } catch (e) {
      setError((e as Error).message)
    } finally {
      setLoading(false)
    }
  }, [customerId, query, onSuccess])

  useEffect(() => { fetchData() }, [fetchData])

  if (loading) {
    return (
      <div className="space-y-2 p-4">
        {[...Array(4)].map((_, i) => (
          <div key={i} className="h-10 animate-pulse rounded-lg bg-elevated" />
        ))}
      </div>
    )
  }

  if (error) {
    return (
      <div className="p-4 text-sm text-red-500 flex items-center gap-2">
        <span>⚠</span> {error}
        <button onClick={fetchData} className="underline ml-2">Retry</button>
      </div>
    )
  }

  return (
    <section className={['space-y-4 p-4', className].filter(Boolean).join(' ')}>
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold text-ink">${item.title}</h2>
        <input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Search accounts…"
          className="h-8 rounded-lg border border-line bg-elevated px-3 text-xs text-ink focus:outline-none"
        />
      </div>
      {data.length === 0 ? (
        <p className="text-ink-3 text-sm py-8 text-center">No accounts found for this customer.</p>
      ) : (
        <ul className="divide-y divide-line">
          {data.map((row: any, i) => (
            <li key={row.id ?? i} className="py-3 flex items-center justify-between hover:bg-elevated/40 px-2 rounded-lg transition-colors">
              <div>
                <span className="text-sm font-medium text-ink font-mono">{row.account_number ?? row.name}</span>
                <p className="text-xs text-ink-3 mt-0.5">{row.channel ?? 'mobile'} · {row.currency ?? 'GBP'}</p>
              </div>
              <span className={\`text-xs font-medium px-2 py-0.5 rounded-full \${
                row.status === 'active'    ? 'bg-success/10 text-success' :
                row.status === 'suspended' ? 'bg-warning/10 text-warning' :
                'bg-elevated text-ink-3'
              }\`}>
                {row.status ?? 'active'}
              </span>
            </li>
          ))}
        </ul>
      )}
    </section>
  )
}`
  }

  if (t.includes("api") || t.includes("route") || t.includes("endpoint") || t.includes("payment") || t.includes("integration") || t.includes("psd2")) {
    return `import { Router, Request, Response } from 'express'
import { authenticate, authorize } from '../middleware/auth'
import { validate } from '../middleware/validate'
import { z } from 'zod'
import { db } from '../lib/db'
import { logger } from '../lib/logger'
// ${item.title}
// WBS: ${item.wbsNumber} | Repo: ${FAKE_REPO}
// PSD2 compliance: all write endpoints require strong customer authentication (SCA)

const router = Router()

const CreateSchema = z.object({
  customerId:    z.string().min(1),
  accountNumber: z.string().regex(/^[A-Z]{2}[0-9A-Z]{13,30}$/, 'IBAN format required'),
  channel:       z.enum(['mobile', 'web', 'api']).default('mobile'),
  currency:      z.string().length(3).default('GBP'),
  consentRef:    z.string().optional(),   // PSD2 consent reference
  metadata:      z.record(z.unknown()).optional().default({}),
})

router.get(
  '/${slug}',
  authenticate,
  authorize(['admin', 'program_manager', 'compliance_officer', 'team_member']),
  async (req: Request, res: Response) => {
    try {
      const { customerId, page = '1', limit = '20', channel } = req.query as Record<string, string>
      const offset = (parseInt(page) - 1) * parseInt(limit)

      const [rows, count] = await Promise.all([
        db.query(
          \`SELECT * FROM ${tbl} WHERE customer_id = $1 \${channel ? 'AND channel = $4' : ''} ORDER BY created_at DESC LIMIT $2 OFFSET $3\`,
          channel ? [customerId, parseInt(limit), offset, channel] : [customerId, parseInt(limit), offset]
        ),
        db.query('SELECT COUNT(*) FROM ${tbl} WHERE customer_id = $1', [customerId]),
      ])

      res.json({
        success: true,
        data:    rows.rows,
        meta:    { total: parseInt(count.rows[0].count), page: parseInt(page), limit: parseInt(limit) },
      })
    } catch (err) {
      logger.error('[${slug}] GET failed', { err })
      res.status(500).json({ success: false, error: 'Internal server error' })
    }
  }
)

router.post(
  '/${slug}',
  authenticate,
  validate(CreateSchema),
  async (req: Request, res: Response) => {
    try {
      const { customerId, accountNumber, channel, currency, consentRef, metadata } = req.body
      const result = await db.query(
        'INSERT INTO ${tbl} (customer_id, account_number, channel, currency, consent_ref, metadata) VALUES ($1, $2, $3, $4, $5, $6) RETURNING *',
        [customerId, accountNumber, channel, currency, consentRef ?? null, JSON.stringify(metadata)]
      )
      logger.info('[${slug}] account created', { id: result.rows[0].id, customerId })
      res.status(201).json({ success: true, data: result.rows[0] })
    } catch (err) {
      logger.error('[${slug}] POST failed', { err })
      res.status(400).json({ success: false, error: (err as Error).message })
    }
  }
)

router.delete(
  '/${slug}/:id',
  authenticate,
  authorize(['admin', 'program_manager']),
  async (req: Request, res: Response) => {
    const { id } = req.params
    await db.query('UPDATE ${tbl} SET status = $1, updated_at = NOW() WHERE id = $2', ['closed', id])
    res.json({ success: true })
  }
)

export default router`
  }

  if (t.includes("service") || t.includes("push") || t.includes("firebase") || t.includes("notification") || t.includes("script") || t.includes("config")) {
    return `import { logger } from '../lib/logger'
import { cache } from '../lib/cache'
// ${item.title}
// WBS: ${item.wbsNumber} | Est: ${item.estimatedHours ?? "?"}h | Repo: ${FAKE_REPO}

interface FindAllParams {
  customerId: string
  page?:      number
  limit?:     number
  channel?:   'mobile' | 'web' | 'api'
}

interface CreatePayload {
  customerId:    string
  accountNumber: string
  channel:       'mobile' | 'web' | 'api'
  fcmToken?:     string    // Firebase Cloud Messaging device token
  currency?:     string
  metadata?:     Record<string, unknown>
}

export class ${name}Service {
  private readonly baseUrl: string
  private readonly apiKey:  string
  private readonly timeout  = 15_000

  constructor(cfg: { baseUrl: string; apiKey: string }) {
    this.baseUrl = cfg.baseUrl.replace(/\/$/, '')
    this.apiKey  = cfg.apiKey
  }

  async findAll(params: FindAllParams) {
    const qs  = new URLSearchParams(params as Record<string, string>).toString()
    const key = \`${slug}:findAll:\${qs}\`
    const hit = await cache.get<unknown[]>(key)
    if (hit) return hit

    const data = await this.request<unknown[]>('GET', \`/accounts?\${qs}\`)
    await cache.set(key, data, 300)
    return data
  }

  async findById(id: string) {
    return this.request<unknown>('GET', \`/accounts/\${id}\`)
  }

  async create(payload: CreatePayload) {
    if (!payload.customerId)    throw new Error('customerId is required')
    if (!payload.accountNumber) throw new Error('accountNumber is required')
    const result = await this.request('POST', '/accounts', {
      ...payload,
      currency: payload.currency ?? 'GBP',
    })
    await cache.invalidatePrefix('${slug}:findAll:')
    return result
  }

  async sendPushNotification(fcmToken: string, notification: { title: string; body: string; data?: Record<string, string> }) {
    if (!fcmToken) throw new Error('fcmToken is required for push delivery')
    logger.info('[${name}Service] sending FCM push', { token: fcmToken.slice(0, 8) + '…' })
    return this.request('POST', '/notifications/push', { fcmToken, ...notification })
  }

  async update(id: string, patch: Partial<CreatePayload>) {
    const result = await this.request('PATCH', \`/accounts/\${id}\`, patch)
    await cache.invalidatePrefix('${slug}:')
    return result
  }

  async delete(id: string) {
    await this.request('DELETE', \`/accounts/\${id}\`)
    await cache.invalidatePrefix('${slug}:')
  }

  private async request<T = unknown>(method: string, path: string, body?: unknown): Promise<T> {
    const ctrl = new AbortController()
    const tid  = setTimeout(() => ctrl.abort(), this.timeout)
    try {
      const res = await fetch(\`\${this.baseUrl}\${path}\`, {
        method,
        headers: {
          'Content-Type':     'application/json',
          'Authorization':    \`Bearer \${this.apiKey}\`,
          'X-Request-Id':     crypto.randomUUID(),
          'X-Service':        '${name}Service',
          'X-Client-Channel': 'api',
        },
        body:   body ? JSON.stringify(body) : undefined,
        signal: ctrl.signal,
      })
      if (!res.ok) {
        const msg = await res.text()
        logger.error(\`[${name}Service] \${method} \${path} →\`, { status: res.status, msg })
        throw new Error(\`HTTP \${res.status}: \${msg}\`)
      }
      return res.json()
    } finally {
      clearTimeout(tid)
    }
  }
}`
  }

  // Default: utility/schema module
  return `import { z } from 'zod'
// ${item.title}
// WBS: ${item.wbsNumber} | Repo: ${FAKE_REPO}

// ─── Schema ──────────────────────────────────────────────────────────────────
export const ${toPascal(slug)}Schema = z.object({
  id:             z.string().uuid(),
  customerId:     z.string().min(1),
  accountId:      z.string().uuid(),
  transactionRef: z.string().optional(),
  channel:        z.enum(['mobile', 'web', 'api']).default('mobile'),
  currency:       z.string().length(3).default('GBP'),
  status:         z.enum(['active', 'suspended', 'closed', 'pending']).default('active'),
  metadata:       z.record(z.unknown()).default({}),
  createdAt:      z.string().datetime(),
  updatedAt:      z.string().datetime(),
})

export type ${name} = z.infer<typeof ${toPascal(slug)}Schema>

// ─── Guards ───────────────────────────────────────────────────────────────────
export function is${name}(data: unknown): data is ${name} {
  return ${toPascal(slug)}Schema.safeParse(data).success
}

export function validate${name}(data: unknown): ${name} {
  return ${toPascal(slug)}Schema.parse(data)
}

// ─── Formatters ───────────────────────────────────────────────────────────────
export function format${name}(item: ${name}): string {
  return \`[\${item.status.toUpperCase()}] \${item.accountId} · \${item.currency} · \${item.channel}\`
}

export function group${name}ByChannel(items: ${name}[]): Record<string, ${name}[]> {
  return items.reduce<Record<string, ${name}[]>>((acc, item) => {
    acc[item.channel] ??= []
    acc[item.channel].push(item)
    return acc
  }, {})
}

// ─── Sorting ─────────────────────────────────────────────────────────────────
export function sort${name}ByDate(items: ${name}[], dir: 'asc' | 'desc' = 'desc'): ${name}[] {
  return [...items].sort((a, b) => {
    const diff = new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()
    return dir === 'asc' ? diff : -diff
  })
}

export function filter${name}(items: ${name}[], status?: string, channel?: string): ${name}[] {
  return items.filter((item) => {
    if (status  && item.status  !== status)  return false
    if (channel && item.channel !== channel) return false
    return true
  })
}`
}

// ─── Status pill ──────────────────────────────────────────────────────────────
const GIT_STATUS_META: Record<GitStatus, { label: string; cls: string }> = {
  idle:       { label: "No code",     cls: "text-ink-3 bg-elevated" },
  generating: { label: "Generating…", cls: "text-warning bg-warning/10" },
  ready:      { label: "Ready",       cls: "text-info bg-info/10" },
  committing: { label: "Committing…", cls: "text-warning bg-warning/10" },
  committed:  { label: "Committed",   cls: "text-success bg-success/10" },
  pushing:    { label: "Pushing…",    cls: "text-warning bg-warning/10" },
  pushed:     { label: "Pushed",      cls: "text-success bg-success/10" },
  pr_created: { label: "PR Open",     cls: "text-success bg-success/10" },
}

function GitStatusPill({ status }: { status: GitStatus }) {
  const meta       = GIT_STATUS_META[status]
  const isSpinning = status === "generating" || status === "committing" || status === "pushing"
  return (
    <span className={cn("inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold", meta.cls)}>
      {isSpinning  && <Loader2     className="h-2.5 w-2.5 animate-spin" />}
      {status === "pr_created" && <CheckCircle2 className="h-2.5 w-2.5" />}
      {meta.label}
    </span>
  )
}

// ─── Terminal log colors ──────────────────────────────────────────────────────
const LOG_CLS: Record<LogEntry["type"], string> = {
  cmd:    "text-[#7DD3FC] font-semibold",
  info:   "text-[#94A3B8]",
  ok:     "text-[#4ADE80]",
  err:    "text-[#F87171]",
  remote: "text-[#C084FC]",
}

// ─── Git flow step indicator ──────────────────────────────────────────────────
const FLOW_STEPS: { key: GitStatus; label: string; icon: typeof GitBranch }[] = [
  { key: "ready",      label: "Code ready",  icon: Code2 },
  { key: "committed",  label: "Committed",   icon: GitCommit },
  { key: "pushed",     label: "Pushed",      icon: Upload },
  { key: "pr_created", label: "PR created",  icon: GitPullRequest },
]

const STEP_ORDER: GitStatus[] = ["idle","generating","ready","committing","committed","pushing","pushed","pr_created"]

function FlowStep({ stepKey, current, label, Icon }: {
  stepKey: GitStatus; current: GitStatus; label: string; Icon: typeof GitBranch
}) {
  const currentIdx = STEP_ORDER.indexOf(current)
  const stepIdx    = STEP_ORDER.indexOf(stepKey)
  const done       = currentIdx > stepIdx
  const active     = current === stepKey ||
    (stepKey === "committed" && current === "committing") ||
    (stepKey === "pushed"    && current === "pushing")
  return (
    <div className={cn("flex items-center gap-1.5 text-[10px]", done || active ? "text-success" : "text-ink-3")}>
      <div className={cn(
        "h-5 w-5 rounded-full flex items-center justify-center shrink-0",
        done   ? "bg-success/20" :
        active ? "bg-warning/20" :
        "bg-elevated"
      )}>
        {done ? <CheckCircle2 className="h-3 w-3 text-success" /> :
         active ? <Loader2 className="h-3 w-3 text-warning animate-spin" /> :
         <Icon className="h-3 w-3" />}
      </div>
      <span className={active ? "text-warning" : ""}>{label}</span>
    </div>
  )
}

// ─── Main Component ───────────────────────────────────────────────────────────
export function DeveloperWorkspace({ projectId }: { projectId: string }) {
  const allItems           = useWorkItems(projectId)
  const { updateWorkItem } = useScheduleStore()

  const devItems = allItems.filter(
    (i) => (i.type === "task" || i.type === "story") && i.assigneeId
  )
  const assignees = MOCK_USERS.filter((u) => devItems.some((i) => i.assigneeId === u.id))

  const [filterAssignee, setFilterAssignee] = useState("all")
  const [selectedId,     setSelectedId]     = useState<string | null>(null)
  const [taskStates,     setTaskStates]     = useState<Record<string, TaskGitState>>({})
  const [copied,         setCopied]         = useState(false)
  const [vsCodeOpen,     setVsCodeOpen]     = useState(false)

  const timerRef      = useRef<ReturnType<typeof setInterval> | null>(null)
  const logRef        = useRef<HTMLDivElement>(null)
  const taskStatesRef = useRef(taskStates)
  taskStatesRef.current = taskStates

  const filtered   = devItems.filter((i) => filterAssignee === "all" || i.assigneeId === filterAssignee)
  const selectedItem = allItems.find((i) => i.id === selectedId) ?? null
  const gs           = selectedId ? (taskStates[selectedId] ?? DEFAULT_STATE) : DEFAULT_STATE

  const patchState = useCallback((id: string, update: Partial<TaskGitState>) => {
    setTaskStates((prev) => ({
      ...prev,
      [id]: { ...(prev[id] ?? DEFAULT_STATE), ...update },
    }))
  }, [])

  const appendLog = useCallback((id: string, entry: LogEntry) => {
    setTaskStates((prev) => {
      const cur = prev[id] ?? DEFAULT_STATE
      return { ...prev, [id]: { ...cur, log: [...cur.log, entry] } }
    })
    setTimeout(() => {
      if (logRef.current) logRef.current.scrollTop = logRef.current.scrollHeight
    }, 30)
  }, [])

  // ── Code generation ─────────────────────────────────────────────────────────
  const startGeneration = useCallback((item: WorkItem) => {
    if (timerRef.current) clearInterval(timerRef.current)

    const fullCode      = generateCode(item)
    const branch        = getBranch(item)
    const commitMessage = getCommitMsg(item)

    patchState(item.id, {
      status: "generating", code: fullCode, displayCode: "",
      branch, commitMessage, commitHash: "", prNumber: 0, log: [],
    })

    let idx = 0
    const CHUNK = 18 // chars per frame ≈ 1 080 chars/s at 60fps
    timerRef.current = setInterval(() => {
      idx += CHUNK
      if (idx >= fullCode.length) {
        clearInterval(timerRef.current!)
        timerRef.current = null
        setTaskStates((prev) => ({
          ...prev,
          [item.id]: { ...(prev[item.id] ?? DEFAULT_STATE), status: "ready", displayCode: fullCode },
        }))
      } else {
        setTaskStates((prev) => ({
          ...prev,
          [item.id]: { ...(prev[item.id] ?? DEFAULT_STATE), displayCode: fullCode.slice(0, idx) },
        }))
      }
    }, 16)
  }, [patchState])

  // Auto-generate when a task is selected and has no code yet
  useEffect(() => {
    if (!selectedId) return
    const existing = taskStatesRef.current[selectedId]
    if (existing && existing.status !== "idle") return
    const item = allItems.find((i) => i.id === selectedId)
    if (item) startGeneration(item)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedId])

  // Cleanup timer when unmounted or task changes
  useEffect(() => () => { if (timerRef.current) clearInterval(timerRef.current) }, [selectedId])

  // ── Commit & push flow ──────────────────────────────────────────────────────
  const handleCommitPush = useCallback(async () => {
    if (!selectedItem || !gs.code) return
    const id      = selectedItem.id
    const branch  = gs.branch        || getBranch(selectedItem)
    const msg     = gs.commitMessage || getCommitMsg(selectedItem)
    const file    = getFileName(selectedItem)
    const lines   = gs.code.split("\n").length
    const inserts = lines

    // 1. Checkout branch
    patchState(id, { status: "committing" })
    appendLog(id, { type: "cmd",  text: `$ git checkout -b ${branch}` })
    await delay(400)
    appendLog(id, { type: "ok",   text: `Switched to a new branch '${branch}'` })

    // 2. Stage file
    appendLog(id, { type: "cmd",  text: `$ git add ${file}` })
    await delay(300)
    appendLog(id, { type: "cmd",  text: `$ git diff --staged --stat` })
    await delay(250)
    appendLog(id, { type: "info", text: ` ${file} | ${inserts} ${"+" .repeat(Math.min(inserts, 24))}` })
    appendLog(id, { type: "info", text: ` 1 file changed, ${inserts} insertions(+)` })

    // 3. Commit
    appendLog(id, { type: "cmd",  text: `$ git commit -m "${msg}"` })
    await delay(700)
    const hash = randomHash()
    patchState(id, { status: "committed", commitHash: hash })
    appendLog(id, { type: "ok",   text: `[${branch} ${hash}] ${msg}` })
    appendLog(id, { type: "info", text: ` 1 file changed, ${inserts} insertions(+)` })

    await delay(500)

    // 4. Push
    patchState(id, { status: "pushing" })
    appendLog(id, { type: "cmd",    text: `$ git push -u origin ${branch}` })
    await delay(400)
    appendLog(id, { type: "info",   text: "Enumerating objects: 5, done." })
    appendLog(id, { type: "info",   text: "Counting objects: 100% (5/5), done." })
    appendLog(id, { type: "info",   text: "Delta compression using up to 8 threads" })
    appendLog(id, { type: "info",   text: "Compressing objects: 100% (3/3), done." })
    await delay(900)
    appendLog(id, { type: "info",   text: `Writing objects: 100% (3/3), ${(inserts * 0.026).toFixed(2)} KiB | ${(inserts * 0.1).toFixed(2)} MiB/s, done.` })
    appendLog(id, { type: "info",   text: `Total 3 (delta 1), reused 0 (delta 0), pack-reused 0` })
    await delay(400)
    appendLog(id, { type: "remote", text: `remote: Resolving deltas: 100% (1/1), done.` })
    appendLog(id, { type: "remote", text: `remote:` })
    appendLog(id, { type: "remote", text: `remote: Create a pull request on GitHub:` })
    appendLog(id, { type: "remote", text: `remote:   ${FAKE_PR_BASE}/new/${branch}` })
    appendLog(id, { type: "remote", text: `remote:` })
    appendLog(id, { type: "ok",     text: `To github.com:${FAKE_REPO}.git` })
    appendLog(id, { type: "ok",     text: ` * [new branch] ${branch} → ${branch}` })
    appendLog(id, { type: "info",   text: `Branch '${branch}' set up to track remote branch '${branch}' from 'origin'.` })
    patchState(id, { status: "pushed" })

    await delay(600)

    // 5. Create PR
    const prNum = Math.floor(Math.random() * 60) + 110
    appendLog(id, { type: "cmd",  text: `$ gh pr create --title "${msg}" --base main` })
    await delay(800)
    appendLog(id, { type: "info", text: `Creating pull request for ${branch} into main in ${FAKE_REPO}` })
    await delay(500)
    appendLog(id, { type: "ok",   text: `✓  Pull request #${prNum} created` })
    appendLog(id, { type: "ok",   text: `   ${FAKE_PR_BASE}/${prNum}` })

    patchState(id, { status: "pr_created", prNumber: prNum })
    updateWorkItem(id, { status: "completed", completionPct: 100 })
  }, [selectedItem, gs, patchState, appendLog, updateWorkItem])

  // ── Actions ─────────────────────────────────────────────────────────────────
  const handleCodeChange = useCallback((value: string) => {
    if (!selectedId) return
    setTaskStates((prev) => {
      const cur = prev[selectedId] ?? DEFAULT_STATE
      return { ...prev, [selectedId]: { ...cur, code: value, displayCode: value } }
    })
  }, [selectedId])

  const handleMsgChange = useCallback((value: string) => {
    if (!selectedId) return
    // Ensure the task state exists before patching so edits are preserved pre-generation
    setTaskStates((prev) => ({
      ...prev,
      [selectedId]: { ...(prev[selectedId] ?? DEFAULT_STATE), commitMessage: value },
    }))
  }, [selectedId])

  const handleRegenerate = useCallback(() => {
    if (!selectedItem) return
    startGeneration(selectedItem)
  }, [selectedItem, startGeneration])

  const handleReset = useCallback(() => {
    if (!selectedId) return
    if (timerRef.current) { clearInterval(timerRef.current); timerRef.current = null }
    patchState(selectedId, DEFAULT_STATE)
    // Re-generate automatically
    const item = allItems.find((i) => i.id === selectedId)
    if (item) setTimeout(() => startGeneration(item), 50)
  }, [selectedId, allItems, patchState, startGeneration])

  const handleCopy = useCallback(() => {
    if (!gs.code) return
    navigator.clipboard.writeText(gs.code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }, [gs.code])

  const handleOpenVSCode = useCallback(() => {
    if (!selectedItem || !gs.code) return
    setVsCodeOpen(true)
  }, [selectedItem, gs.code])

  // ── Derived ─────────────────────────────────────────────────────────────────
  // Branch and commit message are available immediately when a task is selected,
  // falling back to gs values once generation has run and they may have been edited.
  const liveBranch    = gs.branch        || (selectedItem ? getBranch(selectedItem)    : "")
  const liveCommitMsg = gs.commitMessage || (selectedItem ? getCommitMsg(selectedItem) : "")

  const canCommit  = (gs.status === "ready" || gs.status === "committed") &&
    gs.code.length > 0 && liveCommitMsg.length > 0
  const isWorking  = gs.status === "committing" || gs.status === "pushing"
  const fileName   = selectedItem ? getFileName(selectedItem) : ""
  const assignee   = selectedItem ? MOCK_USERS.find((u) => u.id === selectedItem.assigneeId) : null
  const lineCount  = gs.code ? gs.code.split("\n").length : 0

  return (
    <>
    {selectedItem && gs.code && (
      <VsCodeExportModal
        open={vsCodeOpen}
        onClose={() => setVsCodeOpen(false)}
        item={selectedItem}
        code={gs.code}
        fileName={fileName}
        branch={gs.branch || getBranch(selectedItem)}
      />
    )}
    <div className="flex h-full overflow-hidden">
      {/* ── Left: task list ─────────────────────────────────────────────── */}
      <div className="w-64 shrink-0 border-r border-[var(--line)] flex flex-col overflow-hidden">
        <div className="px-3 py-3 border-b border-[var(--line)] space-y-2">
          <p className="text-[10px] uppercase tracking-widest font-semibold text-ink-3">Dev Tasks</p>
          <select
            value={filterAssignee}
            onChange={(e) => setFilterAssignee(e.target.value)}
            className="h-7 w-full rounded-lg border border-[var(--line)] bg-elevated px-2 text-xs text-ink focus:outline-none focus:border-sdp-red"
          >
            <option value="all">All Assignees</option>
            {assignees.map((u) => (
              <option key={u.id} value={u.id}>{u.name}</option>
            ))}
          </select>
        </div>

        <div className="flex-1 overflow-y-auto">
          {filtered.length === 0 ? (
            <p className="text-center text-xs text-ink-3 py-10 px-4">No assigned tasks.</p>
          ) : filtered.map((item) => {
            const st         = taskStates[item.id]?.status ?? "idle"
            const user       = MOCK_USERS.find((u) => u.id === item.assigneeId)
            const isSelected = item.id === selectedId
            return (
              <button
                key={item.id}
                onClick={() => setSelectedId(item.id)}
                className={cn(
                  "w-full text-left px-3 py-2.5 border-b border-[var(--line)] transition-colors",
                  isSelected
                    ? "bg-sdp-red/[0.08] border-l-2 border-l-sdp-red"
                    : "hover:bg-elevated"
                )}
              >
                <div className="flex items-start justify-between gap-1.5 mb-1">
                  <span className="text-xs font-medium text-ink leading-snug line-clamp-2">{item.title}</span>
                  <GitStatusPill status={st} />
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-mono text-ink-3">{item.wbsNumber}</span>
                  {item.storyPoints && <span className="text-[10px] text-ink-3">{item.storyPoints}pt</span>}
                  {user && (
                    <span className="ml-auto text-[10px] text-ink-3 flex items-center gap-0.5">
                      <User className="h-2.5 w-2.5" />{user.name.split(" ")[0]}
                    </span>
                  )}
                </div>
                {st === "pr_created" && (
                  <div className="mt-1 text-[10px] text-success flex items-center gap-1">
                    <CheckCircle2 className="h-2.5 w-2.5" />
                    PR #{taskStates[item.id]?.prNumber} open
                  </div>
                )}
              </button>
            )
          })}
        </div>

        <div className="px-3 py-2.5 border-t border-[var(--line)]">
          <div className="flex items-center gap-2">
            <GitFork className="h-3.5 w-3.5 text-sdp-red shrink-0" />
            <div className="min-w-0">
              <p className="text-[10px] font-semibold text-ink truncate">{FAKE_REPO}</p>
              <p className="text-[10px] text-success flex items-center gap-1">
                <span className="h-1.5 w-1.5 rounded-full bg-success inline-block" />
                {FAKE_USER} · connected
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* ── Right: workspace ────────────────────────────────────────────── */}
      <div className="flex-1 flex flex-col overflow-hidden min-w-0">
        {!selectedItem ? (
          <div className="flex-1 flex flex-col items-center justify-center gap-4 text-center px-8">
            <div className="h-16 w-16 rounded-2xl bg-elevated flex items-center justify-center">
              <Code2 className="h-8 w-8 text-ink-3" />
            </div>
            <div>
              <p className="text-sm font-semibold text-ink">Select a task to start coding</p>
              <p className="text-xs text-ink-3 mt-1 max-w-xs leading-relaxed">
                Code generates automatically. Review it, edit if needed, then commit and push.
              </p>
            </div>
          </div>
        ) : (
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* Task bar */}
            <div className="px-4 py-2.5 border-b border-[var(--line)] flex items-center gap-3 shrink-0">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-mono text-ink-3 shrink-0">{selectedItem.wbsNumber}</span>
                  <h3 className="text-sm font-semibold text-ink truncate">{selectedItem.title}</h3>
                </div>
                <div className="flex items-center gap-3 mt-0.5 text-[10px] text-ink-3">
                  {assignee && <span className="flex items-center gap-1"><User className="h-2.5 w-2.5" />{assignee.name}</span>}
                  {selectedItem.storyPoints && <span>{selectedItem.storyPoints} pts</span>}
                  {selectedItem.estimatedHours && <span>{selectedItem.estimatedHours}h est.</span>}
                  <GitStatusPill status={gs.status} />
                </div>
              </div>
              <div className="flex items-center gap-1.5 shrink-0">
                <Button variant="outline" size="sm" onClick={handleReset} className="h-7 px-2" title="Reset & regenerate">
                  <RotateCcw className="h-3 w-3" />
                </Button>
                <Button
                  variant="outline" size="sm"
                  onClick={handleRegenerate}
                  disabled={gs.status === "generating" || isWorking}
                  className="h-7 gap-1.5 text-xs"
                >
                  <Zap className="h-3 w-3" />
                  Regenerate
                </Button>
              </div>
            </div>

            <div className="flex-1 flex overflow-hidden">
              {/* Code editor */}
              <div className="flex-1 flex flex-col overflow-hidden min-w-0">
                {/* Editor tab bar */}
                <div className="flex items-center bg-[#080F1C] border-b border-[var(--line)] px-2 gap-1 shrink-0">
                  <div className="flex items-center gap-1.5 bg-[#0A0E14] border-t-2 border-t-sdp-red border-x border-[var(--line)] px-3 py-1.5 -mb-px">
                    <FileCode2 className="h-3 w-3 text-ink-3" />
                    <span className="text-[10px] font-mono text-ink truncate max-w-[240px]">{fileName}</span>
                    {gs.status !== "idle" && gs.status !== "generating" && (
                      <span className="ml-1 h-1.5 w-1.5 rounded-full bg-warning shrink-0" title="Unsaved" />
                    )}
                  </div>
                  <div className="ml-auto flex items-center gap-0.5 px-1">
                    {lineCount > 0 && (
                      <span className="text-[10px] text-ink-3 font-mono mr-2">{lineCount}L</span>
                    )}
                    <button
                      onClick={handleCopy}
                      disabled={!gs.code}
                      className="flex items-center gap-1 px-2 py-1 rounded text-[10px] text-ink-3 hover:text-ink hover:bg-elevated transition-colors disabled:opacity-40"
                    >
                      {copied ? <CheckCircle2 className="h-3 w-3 text-success" /> : <Copy className="h-3 w-3" />}
                      {copied ? "Copied!" : "Copy"}
                    </button>
                    <button
                      onClick={handleOpenVSCode}
                      disabled={!gs.code}
                      className="flex items-center gap-1.5 px-2.5 py-1 rounded text-[10px] font-semibold text-[#007ACC] hover:bg-[#007ACC]/10 transition-colors disabled:opacity-40 border border-[#007ACC]/30 hover:border-[#007ACC]/60"
                    >
                      <svg width="11" height="11" viewBox="0 0 100 100" fill="none" className="shrink-0">
                        <path d="M74.9 7.5L50 31.3 25 7.5 0 25v50l25 17.5 25-23.8 25 23.8 25-17.5V25L74.9 7.5z" fill="#007ACC"/>
                        <path d="M74.9 7.5L50 31.3V68.8L74.9 92.5 100 75V25L74.9 7.5z" fill="#1BA1E2"/>
                        <path d="M25 7.5v85L0 75V25L25 7.5z" fill="#0065A9"/>
                      </svg>
                      Open in VS Code
                    </button>
                  </div>
                </div>

                {/* Editor body — always shows textarea once code is generating */}
                <div className="flex-1 relative overflow-hidden bg-[#0A0E14]">
                  <textarea
                    value={gs.displayCode}
                    onChange={(e) => handleCodeChange(e.target.value)}
                    spellCheck={false}
                    placeholder={gs.status === "idle" ? "Generating code…" : ""}
                    className={cn(
                      "absolute inset-0 w-full h-full resize-none font-mono text-xs leading-[1.6] caret-[#7DD3FC]",
                      "bg-transparent text-[#E2EBF7] p-4 focus:outline-none selection:bg-sdp-red/25",
                      "placeholder:text-ink-3",
                    )}
                  />
                  {gs.status === "generating" && (
                    <div className="absolute bottom-3 right-3 flex items-center gap-1.5 bg-[#0F2240]/90 backdrop-blur-sm rounded-full px-3 py-1.5 text-xs text-warning border border-warning/20">
                      <Loader2 className="h-3 w-3 animate-spin" />
                      AI writing code…
                    </div>
                  )}
                </div>
              </div>

              {/* Right panel: git + terminal */}
              <div className="w-68 shrink-0 border-l border-[var(--line)] flex flex-col overflow-hidden" style={{ width: "272px" }}>
                {/* Delivery flow steps */}
                <div className="px-4 pt-3 pb-2 border-b border-[var(--line)] space-y-2">
                  <p className="text-[10px] uppercase tracking-widest font-semibold text-ink-3">Delivery Flow</p>
                  <div className="space-y-1.5">
                    {FLOW_STEPS.map((step) => (
                      <FlowStep
                        key={step.key}
                        stepKey={step.key}
                        current={gs.status}
                        label={step.label}
                        Icon={step.icon}
                      />
                    ))}
                  </div>
                </div>

                {/* Git config */}
                <div className="px-4 py-3 border-b border-[var(--line)] space-y-2.5">
                  <p className="text-[10px] uppercase tracking-widest font-semibold text-ink-3 flex items-center gap-1.5">
                    <GitBranch className="h-3 w-3" /> Git
                  </p>

                  <div>
                    <p className="text-[10px] text-ink-3 mb-1">Branch</p>
                    <div className={cn(
                      "flex items-center gap-1.5 h-7 rounded-lg border px-2 transition-colors",
                      liveBranch ? "border-sdp-red/30 bg-[#060D1A]" : "border-[var(--line)] bg-[#060D1A]"
                    )}>
                      <GitBranch className={cn("h-3 w-3 shrink-0", liveBranch ? "text-sdp-red" : "text-ink-3")} />
                      <span className="text-[10px] font-mono text-ink truncate">
                        {liveBranch || "—"}
                      </span>
                    </div>
                  </div>

                  <div>
                    <p className="text-[10px] text-ink-3 mb-1">Commit message</p>
                    <input
                      value={liveCommitMsg}
                      onChange={(e) => handleMsgChange(e.target.value)}
                      disabled={isWorking || gs.status === "pr_created"}
                      placeholder="feat: describe change…"
                      className={cn(
                        "h-7 w-full rounded-lg border border-[var(--line)] bg-[#060D1A] px-2 text-[10px] text-ink font-mono",
                        "placeholder:text-ink-3 focus:outline-none focus:border-sdp-red transition-colors",
                        "disabled:opacity-50"
                      )}
                    />
                  </div>

                  {gs.commitHash && (
                    <div className="flex items-center gap-1.5 text-[10px]">
                      <GitCommit className="h-3 w-3 text-success shrink-0" />
                      <span className="font-mono text-success">{gs.commitHash}</span>
                      <span className="text-ink-3">on {liveBranch.slice(0, 16)}…</span>
                    </div>
                  )}

                  {gs.status === "pr_created" ? (
                    <div className="rounded-lg border border-success/30 bg-success/5 p-2.5 space-y-1.5">
                      <div className="flex items-center gap-1.5 text-[10px] text-success font-semibold">
                        <GitMerge className="h-3 w-3" /> PR #{gs.prNumber} · Open
                      </div>
                      <a
                        href={`${FAKE_PR_BASE}/${gs.prNumber}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center gap-1 text-[10px] text-info hover:underline"
                      >
                        <ExternalLink className="h-2.5 w-2.5" />
                        View on GitHub
                      </a>
                    </div>
                  ) : (
                    <Button
                      variant="primary" size="sm"
                      onClick={handleCommitPush}
                      disabled={!canCommit || isWorking}
                      className="w-full h-8 gap-1.5 text-xs"
                    >
                      {isWorking ? (
                        <>
                          <Loader2 className="h-3 w-3 animate-spin" />
                          {gs.status === "committing" ? "Committing…" : "Pushing…"}
                        </>
                      ) : (
                        <>
                          <Upload className="h-3 w-3" />
                          Commit & Push
                        </>
                      )}
                    </Button>
                  )}
                </div>

                {/* Terminal */}
                <div className="flex-1 overflow-hidden flex flex-col bg-[#030810]">
                  <div className="flex items-center gap-1.5 px-3 py-1.5 border-b border-[var(--line)] shrink-0">
                    <div className="flex gap-1 mr-1">
                      <div className="h-2 w-2 rounded-full bg-[#FF5F57]" />
                      <div className="h-2 w-2 rounded-full bg-[#FFBD2E]" />
                      <div className="h-2 w-2 rounded-full bg-[#28CA41]" />
                    </div>
                    <Terminal className="h-3 w-3 text-ink-3" />
                    <span className="text-[10px] text-ink-3 font-mono">bash — {FAKE_REPO}</span>
                  </div>
                  <div
                    ref={logRef}
                    className="flex-1 overflow-y-auto px-3 py-2 font-mono text-[10px] leading-5 space-y-0"
                  >
                    {gs.log.length === 0 ? (
                      <span className="text-[#3D5470]">
                        {gs.status === "ready" ? `$ _` : "Waiting…"}
                      </span>
                    ) : (
                      gs.log.map((entry, i) => (
                        <div key={i} className={LOG_CLS[entry.type]}>{entry.text}</div>
                      ))
                    )}
                    {isWorking && <span className="text-[#3D5470] animate-pulse">▋</span>}
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
    </>
  )
}

function delay(ms: number) {
  return new Promise<void>((r) => setTimeout(r, ms))
}
