import type { RaidItem, Escalation } from "../types"

export const MOCK_RAID_ITEMS: RaidItem[] = [
  {
    id: "raid-001",
    projectId: "prj-001",
    type: "risk",
    title: "PCI-DSS compliance gap — payment data tokenisation not certified",
    description: "Third-party tokenisation provider has not yet achieved PCI-DSS Level 1 certification for the new instant payment flow. Certification audit is scheduled for August but results are uncertain.",
    status: "escalated",
    priority: "critical",
    ownerId: "usr-001",
    dueDate: "2024-07-15",
    impact: "Potential 8-week delay to Mobile App Beta Release (M1). Legal liability if uncertified payment flow reaches production.",
    probability: "high",
    responsePlan: "Engage alternative certified tokenisation vendor (Braintree or Adyen) as fallback. Fast-track audit liaison. Conduct internal pre-audit gap assessment.",
    escalatedAt: "2024-06-20T14:00:00Z",
    tags: ["PCI-DSS", "compliance", "payments", "milestone"],
    createdAt: "2024-06-01T10:00:00Z",
    updatedAt: "2024-06-20T14:00:00Z",
  },
  {
    id: "raid-002",
    projectId: "prj-001",
    type: "risk",
    title: "Legacy core banking API rate limits blocking real-time balance sync",
    description: "Meridian Bank's legacy Temenos T24 core banking system imposes a 200 req/min rate cap. At projected user concurrency, real-time balance queries during peak hours will be throttled, causing stale data for up to 45 seconds.",
    status: "in_progress",
    priority: "high",
    ownerId: "usr-003",
    dueDate: "2024-08-01",
    impact: "Degraded UX for account overview and transaction history features. Potential regulatory non-compliance for real-time balance disclosure.",
    probability: "high",
    responsePlan: "Implement Redis caching layer with 30-second TTL. Negotiate rate limit increase with core banking team. Evaluate read-replica API for non-critical queries.",
    tags: ["core-banking", "API", "performance", "caching"],
    createdAt: "2024-06-05T09:00:00Z",
    updatedAt: "2024-06-18T11:00:00Z",
  },
  {
    id: "raid-003",
    projectId: "prj-001",
    type: "assumption",
    title: "Biometric SDK licensing covers iOS and Android without additional cost",
    description: "Assuming the enterprise biometric authentication SDK (BioCatch) license already procured by Meridian Bank covers both iOS Face ID/Touch ID and Android fingerprint/PIN flows. Licensing terms have not been formally verified with procurement.",
    status: "open",
    priority: "high",
    ownerId: "usr-003",
    dueDate: "2024-07-01",
    tags: ["biometric", "licensing", "SDK", "iOS", "Android"],
    createdAt: "2024-05-20T09:00:00Z",
    updatedAt: "2024-06-10T09:00:00Z",
  },
  {
    id: "raid-004",
    projectId: "prj-001",
    type: "issue",
    title: "OAuth 2.0 session token refresh failing in staging — blocking Sprint 8",
    description: "The OAuth 2.0 token refresh flow is throwing 401 Unauthorized errors intermittently in the staging environment after approximately 14 minutes of inactivity. Root cause suspected to be clock skew between the identity provider (Auth0) and the API gateway.",
    status: "in_progress",
    priority: "critical",
    ownerId: "usr-005",
    dueDate: "2024-06-28",
    impact: "Blocking Sprint 8 completion. Affects biometric login (wi-003), MFA (wi-015), and transaction history (wi-013). 7 user stories unable to complete UAT.",
    tags: ["OAuth", "authentication", "staging", "blocker", "Auth0"],
    createdAt: "2024-06-15T16:00:00Z",
    updatedAt: "2024-06-22T09:30:00Z",
  },
  {
    id: "raid-005",
    projectId: "prj-001",
    type: "decision",
    title: "Approved: Phased mobile release — internal beta first, then public App Store",
    description: "Steering committee approved a two-phase mobile release: internal Meridian Bank staff beta (TestFlight / Firebase App Distribution) on July 31, followed by public App Store and Google Play release on September 15 pending QA sign-off.",
    status: "closed",
    priority: "high",
    ownerId: "usr-001",
    closedAt: "2024-06-10T17:00:00Z",
    closureNote: "Decision recorded. Mobile workstream schedule updated. Client VP (Diana Foster) notified. Store listing preparation begins July 1.",
    tags: ["mobile", "release", "strategy", "steering-committee"],
    createdAt: "2024-06-07T09:00:00Z",
    updatedAt: "2024-06-10T17:00:00Z",
  },
  {
    id: "raid-006",
    projectId: "prj-001",
    type: "assumption",
    title: "Meridian Bank IT will provision PSD2 sandbox credentials by June 28",
    description: "Program assumes Meridian Bank's IT Security team will issue PSD2 open banking sandbox API credentials (client_id, client_secret, MTLS certificates) to the Slalom team by end of Sprint 8 to enable Sprint 9 payment hub integration.",
    status: "open",
    priority: "high",
    ownerId: "usr-006",
    dueDate: "2024-06-28",
    tags: ["PSD2", "open-banking", "credentials", "dependency"],
    createdAt: "2024-05-15T09:00:00Z",
    updatedAt: "2024-06-01T09:00:00Z",
  },
  {
    id: "raid-007",
    projectId: "prj-001",
    type: "risk",
    title: "App Store review delay for biometric authentication changes",
    description: "Apple and Google Play have historically taken 5–14 business days to review apps with major biometric or authentication changes. An unexpected rejection could push the beta release past the July 31 milestone.",
    status: "open",
    priority: "medium",
    ownerId: "usr-001",
    dueDate: "2024-07-10",
    impact: "Up to 3-week delay to M1 if App Store review is rejected and resubmission required",
    probability: "medium",
    responsePlan: "Submit for review by July 10 to allow buffer. Prepare pre-submission checklist aligned with Apple's biometric guideline §3.1.4. Maintain TestFlight beta as fallback demonstration path.",
    tags: ["App-Store", "review", "Apple", "Google-Play", "milestone"],
    createdAt: "2024-06-10T09:00:00Z",
    updatedAt: "2024-06-10T09:00:00Z",
  },
  {
    id: "raid-008",
    projectId: "prj-001",
    type: "issue",
    title: "Penetration test not scheduled — required before online banking portal go-live",
    description: "External penetration test (OWASP ASVS Level 2) required by Meridian Bank's information security policy before the Online Banking Portal Go-Live (M2, October 1). The appointed vendor (NCC Group) is not available until late September, leaving zero buffer if findings require remediation.",
    status: "open",
    priority: "high",
    ownerId: "usr-003",
    dueDate: "2024-07-01",
    tags: ["security", "pentest", "OWASP", "compliance", "M2"],
    createdAt: "2024-06-18T09:00:00Z",
    updatedAt: "2024-06-18T09:00:00Z",
  },
  {
    id: "raid-009",
    projectId: "prj-001",
    type: "decision",
    title: "Approved: Adopt Auth0 as identity provider across mobile and web",
    description: "Architecture board approved Auth0 (Okta) as the unified identity provider for both the iOS/Android mobile app and the online banking portal, replacing Meridian Bank's legacy on-premise LDAP-based authentication. Supports OIDC, MFA (TOTP, SMS), and biometric passkey flows.",
    status: "closed",
    priority: "high",
    ownerId: "usr-005",
    closedAt: "2024-05-28T15:00:00Z",
    closureNote: "Auth0 enterprise tenant provisioned. Integration design underway. LDAP migration plan to be drafted by June 30.",
    tags: ["architecture", "Auth0", "identity", "OIDC", "MFA"],
    createdAt: "2024-05-20T09:00:00Z",
    updatedAt: "2024-05-28T15:00:00Z",
  },
  {
    id: "raid-010",
    projectId: "prj-001",
    type: "risk",
    title: "Senior iOS engineer single point of failure for biometric authentication workstream",
    description: "Priya Sharma is the sole engineer with deep iOS Security framework and LocalAuthentication API experience. If she is unavailable during the critical biometric implementation phase (June–July), there is no qualified backup on the current team.",
    status: "open",
    priority: "high",
    ownerId: "usr-001",
    dueDate: "2024-07-10",
    impact: "Potential 4–6 week delay to biometric authentication (wi-003) and Mobile App Beta Release (M1)",
    probability: "medium",
    responsePlan: "Arrange knowledge transfer to at least one junior iOS developer. Document LocalAuthentication integration patterns in Confluence. Identify a contractor as on-call backup (2-week engagement lead time).",
    tags: ["resourcing", "iOS", "biometric", "single-point-of-failure"],
    createdAt: "2024-06-20T09:00:00Z",
    updatedAt: "2024-06-20T09:00:00Z",
  },
]

export const MOCK_ESCALATIONS: Escalation[] = [
  {
    id: "esc-001",
    projectId: "prj-001",
    raidItemId: "raid-001",
    title: "PCI-DSS Tokenisation Risk — Executive Escalation",
    description: "Tokenisation provider certification risk requires executive decision on vendor strategy — proceed with primary vendor at risk, or immediately engage certified fallback (Adyen) at increased cost.",
    level: "executive",
    ownerId: "usr-001",
    escalatedToId: "usr-007",
    status: "in_progress",
    triggerCondition: "Certification outcome uncertainty > 60% likelihood of miss with < 8 weeks to M1",
    slaHours: 48,
    createdAt: "2024-06-20T14:00:00Z",
  },
  {
    id: "esc-002",
    projectId: "prj-001",
    raidItemId: "raid-004",
    title: "OAuth Staging Blocker — P1 Sprint Issue",
    description: "Auth0 token refresh failure blocking 7 user stories in Sprint 8. Development team requires Auth0 enterprise support engagement and coordination with Meridian Bank's API gateway team to resolve clock skew.",
    level: "pm",
    ownerId: "usr-005",
    escalatedToId: "usr-003",
    status: "in_progress",
    triggerCondition: "Blocker unresolved > 2 business days, sprint completion at risk",
    slaHours: 24,
    createdAt: "2024-06-22T10:00:00Z",
  },
]
